# Generated by Django 3.1 on 2021-04-21 21:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('door', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('totDevices', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Not specified')], max_length=20, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('role', models.CharField(blank=True, choices=[('A', 'Admin'), ('C', 'Client'), ('S', 'Shop')], max_length=10, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechSekai.address')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='TechSekai.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechSekai.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=35, primary_key=True, serialize=False)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('website', models.URLField(max_length=40)),
                ('opening_hours', models.TimeField(null=True)),
                ('certified', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TechSekai.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechSekai.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=300)),
                ('warehouse', models.CharField(max_length=50)),
                ('qty_sold', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechSekai.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechSekai.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('order_state', models.CharField(choices=[('ORDERED', 'Processing order'), ('DISPATCHED', 'Sent to delivery'), ('IN TRANSIT', 'On the way'), ('DELIVERED', 'Delivered at the destination address'), ('REFUND', 'Pay back to a non satisfied client'), ('FAILED', 'Error with the destination address, must contact us')], max_length=20)),
                ('payment_meth', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('ATM ', 'ATM')], max_length=20)),
                ('items', models.ManyToManyField(to='TechSekai.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechSekai.user')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TechSekai.product'),
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechSekai.shop'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('items', models.ManyToManyField(to='TechSekai.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechSekai.user')),
            ],
        ),
    ]
