# Generated by Django 3.1.7 on 2021-04-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSekai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='certified',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_meth',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('ATM ', 'ATM'), ('VISA', 'VISA'), ('ApplePay', 'ApplePay')], max_length=20),
        ),
    ]
