# Generated by Django 3.1.7 on 2021-04-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSekai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='./static/imgs/logo.png', null=True, upload_to=''),
        ),
    ]
