# Generated by Django 3.1.7 on 2021-04-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSekai', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='logo.png', null=True, upload_to=''),
        ),
    ]
